@startuml

title "Deposit"

actor "User" as u

participant "Wallet" as wallet
participant "Ledger" as ledger
participant "FireBlocks" as fb
participant "ETH blockchain" as eb

note over u: User has deposit address

u -> eb: User send funds to eth deposit address
eb -> fb: New blocks mined
fb -> fb: analyse the block
alt deposit address detected
fb -> wallet: Webhook call
wallet -> eb: Fetch block
wallet -> wallet: Analyse block and get\nthe balance of deposit address
wallet -> ledger: add balance to user
wallet -> u: Notify user\nabout deposit
else deposit not detected
loop for each new block
fb -> eb : analyse the block
end
end group
@enduml
