@@startuml


:User: as u

rectangle "3rd-Parties" #line.dashed {
    component "FireBlocks" as f #palegreen
    component "OKex" as o #palegreen
}

skinparam rectangle {
    from up to down
}

component "Marketplace" as marketplace #LightBlue
component "Swaps" as swaps #LightBlue
component "Wallet" as wallet #LightBlue
component "Ledger" as ledger

note top of wallet
- Assets management
- Deposit
- Sendout
- Internal Transfer
- Transaction History
- Fueling/Sweeping
- maitenance tooling
end note

note top of ledger
- user money flow
- money flow audit
- balance change history
end note

note right of o
- swaps provider
end note

note right of f
- blockchain and wallet provider
end note

u -up-> wallet: request
wallet -left-> ledger

' small hack to hame boxies vertical order
f .. o #white

wallet => f: API/Webhooks
wallet => o: API/Webhooks

marketplace -up-> ledger: manage user balances
swaps -up-> ledger: manage user balances

@@enduml