@@startuml


:User: as u

rectangle "3rd-Parties" #line.dashed {
    component "FireBlocks" as f #palegreen
    component "OKex" as o #palegreen
}

skinparam rectangle {
    from up to down
}

component "Account" as account #LightBlue
component "Marketplace" as marketplace #LightBlue
component "Swaps" as swaps #LightBlue
component "Wallet" as wallet #LightBlue
component "Ledger" as ledger #LightBlue
component "Account" as account #LightBlue
database "Wallet DB" as wallet_db #LightCyan
database "Wallet Redis" as wallet_cache #LightCyan
database "Ledger DB" as ledger_db #LightCyan


note top of wallet
- Assets management
- Deposit
- Sendout
- Internal Transfer
- Transaction History
- Fueling/Sweeping
- maitenance tooling
end note

note top of ledger
- user money flow
- money flow audit
- balance change history
end note

note right of o
- swaps provider
end note

note right of f
- blockchain and wallet provider
end note

u --down-> wallet: request
wallet -left-> ledger

' small hack to hame boxies vertical order
f .. o #white

wallet => f: API/Webhooks
wallet => o: API/Webhooks

marketplace -up-> ledger: manage user balances
swaps -up-> ledger: manage user balances

wallet =down=> wallet_db
wallet =down=> wallet_cache
wallet =down=> account

ledger =down=> ledger_db

@@enduml