@startuml

title "Deposit"

actor "User" as u

participant "Wallet" as wallet
participant "Ledger" as ledger
participant "FireBlocks" as fb
participant "ETH blockchain" as eb

note over u: User has deposit address

u -> eb: User send funds to eth deposit address
eb -> fb: New block mined

alt deposit address detected
fb -> wallet++: Webhook call
wallet -> eb: Fetch block
wallet -> wallet: Analyse block and get\nthe balance of deposit address
wallet -> ledger: Update user balance
wallet -> u--: Notify user\nabout deposit
end group

@enduml